### ISSUE TITLE
DAG object hass no attribute update_relative

### ISSUE THREAD

**Issue by programmeddeath1** [bryzgaloff/airflow-clickhouse-plugin#55]
Iv installed clickhouse plugin and am trying to run the example mysql to clickhouse

The DAG is giving error 
```Broken DAG: [/opt/airflow/dags/mysqltoclickhouse.py] Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskmixin.py", line 238, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskmixin.py", line 175, in _set_relatives
    task_object.update_relative(self, not upstream)
AttributeError: 'DAG' object has no attribute 'update_relative'
```
Im on python 3.7 and airflow 2.4.3

Can anyone help me figure out what the issue is?
Thanks in advance!

**Comment by programmeddeath1** [comment]
Is an airflow version issue, can add dag as a parameter in operator
