### ISSUE TITLE
Unable to connect to clickhouse server

### ISSUE THREAD

**Issue by programmeddeath1** [bryzgaloff/airflow-clickhouse-plugin#56]
Tryig to run clickhouse plugin on airflow 2.4.3. Installed the plugin using _pip_requirements in docker.

Iv given the connection parameters as sqlite. It is not able to connect to clickhouse.

Is there any connection setup needed at the clickhouse end?

Connection to clickhouse fails to even read table with buffer end error
```[2022-12-12, 07:16:59 UTC] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow_clickhouse_plugin/operators/clickhouse_operator.py", line 33, in execute
    return hook.run(self._sql, self._parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow_clickhouse_plugin/hooks/clickhouse_hook.py", line 72, in run
    types_check=types_check,
  File "/home/airflow/.local/lib/python3.7/site-packages/clickhouse_driver/client.py", line 345, in execute
    with self.disconnect_on_error(query, settings):
  File "/usr/local/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/airflow/.local/lib/python3.7/site-packages/clickhouse_driver/client.py", line 289, in disconnect_on_error
    self.establish_connection(settings)
  File "/home/airflow/.local/lib/python3.7/site-packages/clickhouse_driver/client.py", line 276, in establish_connection
    self.connection.force_connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/clickhouse_driver/connection.py", line 235, in force_connect
    self.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/clickhouse_driver/connection.py", line 342, in connect
    return self._init_connection(host, port)
  File "/home/airflow/.local/lib/python3.7/site-packages/clickhouse_driver/connection.py", line 318, in _init_connection
    self.receive_hello()
  File "/home/airflow/.local/lib/python3.7/site-packages/clickhouse_driver/connection.py", line 421, in receive_hello
    packet_type = read_varint(self.fin)
  File "clickhouse_driver/varint.pyx", line 62, in clickhouse_driver.varint.read_varint
  File "clickhouse_driver/bufferedreader.pyx", line 55, in clickhouse_driver.bufferedreader.BufferedReader.read_one
  File "clickhouse_driver/bufferedreader.pyx", line 240, in clickhouse_driver.bufferedreader.BufferedSocketReader.read_into_buffer
EOFError: Unexpected EOF while reading bytes
```

ERROR - Failed to execute job 9 for task select_users (Unexpected EOF while reading bytes; 2927)

**Comment by programmeddeath1** [comment]
Was using port 8123 instead of 9000
