### ISSUE TITLE
Object of type datetime is not json serializable

### ISSUE THREAD

**Issue by programmeddeath1** [bryzgaloff/airflow-clickhouse-plugin#57]
When trying to run a select query on a clickhouse table with a datetime variable it fails as below
```
[2022-12-12, 07:32:02 UTC] {xcom.py:600} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2022-12-12, 07:32:02 UTC] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2385, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 212, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 597, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
```

How can i handle datetime variable separately?

**Comment by bryzgaloff** [comment]
This is not an Airflow ClickHouse Plugin specific issue: you have misused Airflow XComs. Read about them here: https://airflow.apache.org/docs/apache-airflow/stable/concepts/xcoms.html

Probably your operator has returned a value and one of the fields is of type `datetime`. This type is not JSON serializeable. In your ClickHouse query convert the datetime value into a string using `toString` function of ClickHouse.
