### ISSUE TITLE
AttributeError: 'int' object has no attribute 'encode'

### ISSUE THREAD

**Issue by programmeddeath1** [bryzgaloff/airflow-clickhouse-plugin#58]
Insert into a clickhouse table with int data is giving an encoding error.

```
[2022-12-12, 07:56:58 UTC] {clickhouse_hook.py:84} INFO - INSERT INTO table VALUES with ((1, 'Default manager', None, 'user@dummy.com', None, 1, datetime.datetime(2020, 2, 3, 10, 29, 34), 2),)
[2022-12-12, 07:56:58 UTC] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/mysqltoclickhouse.py", line 18, in mysql_to_clickhouse
    ch_hook.run('INSERT INTO fm_revive.rv_agency VALUES', records)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow_clickhouse_plugin/hooks/clickhouse_hook.py", line 72, in run
    types_check=types_check,
  File "/home/airflow/.local/lib/python3.7/site-packages/clickhouse_driver/client.py", line 354, in execute
    columnar=columnar
  File "/home/airflow/.local/lib/python3.7/site-packages/clickhouse_driver/client.py", line 579, in process_insert_query
    types_check=types_check, columnar=columnar)
  File "/home/airflow/.local/lib/python3.7/site-packages/clickhouse_driver/client.py", line 631, in send_data
    self.connection.send_data(block)
  File "/home/airflow/.local/lib/python3.7/site-packages/clickhouse_driver/connection.py", line 604, in send_data
    self.block_out.write(block)
  File "/home/airflow/.local/lib/python3.7/site-packages/clickhouse_driver/streams/native.py", line 39, in write
    self.fout, types_check=block.types_check)
  File "/home/airflow/.local/lib/python3.7/site-packages/clickhouse_driver/columns/service.py", line 157, in write_column
    column.write_data(items, buf)
  File "/home/airflow/.local/lib/python3.7/site-packages/clickhouse_driver/columns/base.py", line 87, in write_data
    self._write_data(items, buf)
  File "/home/airflow/.local/lib/python3.7/site-packages/clickhouse_driver/columns/base.py", line 91, in _write_data
    self.write_items(prepared, buf)
  File "/home/airflow/.local/lib/python3.7/site-packages/clickhouse_driver/columns/stringcolumn.py", line 18, in write_items
    buf.write_strings(items, encoding=self.encoding)
  File "clickhouse_driver/bufferedwriter.pyx", line 54, in clickhouse_driver.bufferedwriter.BufferedWriter.write_strings
AttributeError: 'int' object has no attribute 'encode'
```

How can i bypass or handle this error?

**Comment by bryzgaloff** [comment]
This is not an Airflow ClickHouse Plugin related issue, you have probably misused the `clickhouse-driver` functionality itself. I think you have mixed the arguments order: the `write_strings` method writes strings and some of your inserted values are `int`s so check your arguments order.
