### ISSUE TITLE
Issue: Integration tests failing due to connection...

### ISSUE THREAD

**Issue by markusf1895** [bryzgaloff/airflow-clickhouse-plugin#76]
Description:
When attempting to run integration tests using the provided command, the tests fail with a connection error. The integration tests utilize ClickHouse for database operations, and the error indicates a failure to connect to localhost:9000. However, it is observed that accessing http://localhost:9000/ directly works as expected, indicating that the port is accessible.

[Archive.zip](https://github.com/bryzgaloff/airflow-clickhouse-plugin/files/14225234/Archive.zip)

Steps to Reproduce:
- extract content of Archive.zip to a folder with name FOLDERNAME
- open terminal in FOLDERNAME
- run "docker compose build"
- run "docker compose up"
- open docker exec of FOLDERNAME-airflow-webserver-1
- run "python3 -m unittest discover -t tests -s unit" => works
- run "docker run -p 9000:9000 --ulimit nofile=262144:262144 -it clickhouse/clickhouse-server" in normal terminal
- run "PYTHONPATH=src AIRFLOW_CONN_CLICKHOUSE_DEFAULT=clickhouse://localhost python3 -m unittest discover -t tests -s integration" in docker exec

Actual Behavior:
Integration tests fail with the following error message:
[2024-02-09T18:20:29.196+0000] {base.py:83} INFO - Using connection ID 'clickhouse_default' for task execution.
[2024-02-09T18:20:29.197+0000] {clickhouse.py:79} INFO - SELECT sum(value) * %(multiplier)s AS output FROM ext with {'multiplier': 2}
[2024-02-09T18:20:29.201+0000] {connection.py:407} WARNING - Failed to connect to localhost:9000
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 395, in connect
    return self._init_connection(host, port)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 325, in _init_connection
    self.socket = self._create_socket(host, port)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 297, in _create_socket
    raise err
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 288, in _create_socket
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

Environment:
Operating System: macOS Sonoma Version 14.3.1
Python Version: 3.8
ClickHouse Version: latest
Airflow Version: 2.8.1
This adjustment will ensure consistency and reliability in running integration tests against ClickHouse databases.

**Comment by markusf1895** [comment]
also tried ClickHouse Version
ClickHouse client version 23.12.4.15 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 23.12.4.

Actual Behavior: Then:
```
(airflow)python3 -m unittest discover -t tests -s unit
.[2024-02-10T01:01:58.905+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-02-10T01:01:58.906+0000] {clickhouse.py:79} INFO - SELECT 1 with [('test-param', 1)]
[2024-02-10T01:01:58.906+0000] {clickhouse.py:79} INFO - SELECT 2 with [('test-param', 1)]
.[2024-02-10T01:01:58.908+0000] {clickhouse.py:79} INFO - SELECT 1
............/opt/airflow/tests/unit/sensors/test_clickhouse.py:82 DeprecationWarning: Please use assertRaisesRegex instead.
...
----------------------------------------------------------------------
Ran 17 tests in 0.208s

OK
(airflow)PYTHONPATH=src AIRFLOW_CONN_CLICKHOUSE_DEFAULT=clickhouse://localhost python3 -m unittest discover -t tests -s integration
[2024-02-10T01:02:12.432+0000] {base.py:83} INFO - Using connection ID 'clickhouse_default' for task execution.
[2024-02-10T01:02:12.433+0000] {clickhouse.py:79} INFO - SELECT sum(value) * %(multiplier)s AS output FROM ext with {'multiplier': 2}
[2024-02-10T01:02:12.434+0000] {connection.py:407} WARNING - Failed to connect to localhost:9000
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 395, in connect
    return self._init_connection(host, port)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 325, in _init_connection
    self.socket = self._create_socket(host, port)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 297, in _create_socket
    raise err
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 288, in _create_socket
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
E[2024-02-10T01:02:12.436+0000] {base.py:83} INFO - Using connection ID 'clickhouse_default' for task execution.
[2024-02-10T01:02:12.436+0000] {sql.py:450} INFO - Running statement: 
                SELECT number * %(multiplier)s AS output
                FROM system.numbers
                LIMIT 1 OFFSET 1
            , parameters: {'multiplier': 2}
[2024-02-10T01:02:12.436+0000] {connection.py:407} WARNING - Failed to connect to localhost:9000
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 395, in connect
    return self._init_connection(host, port)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 325, in _init_connection
    self.socket = self._create_socket(host, port)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 297, in _create_socket
    raise err
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 288, in _create_socket
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
E
======================================================================
ERROR: test_execute (integration.hooks.test_clickhouse.ClickHouseHookTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/airflow/tests/integration/hooks/test_clickhouse.py", line 8, in test_execute
    return_value = ClickHouseHook().execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow_clickhouse_plugin/hooks/clickhouse.py", line 80, in execute
    last_result = conn.execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 361, in execute
    with self.disconnect_on_error(query, settings):
  File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 305, in disconnect_on_error
    self.establish_connection(settings)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 292, in establish_connection
    self.connection.force_connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 254, in force_connect
    self.connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 416, in connect
    raise err
clickhouse_driver.errors.NetworkError: Code: 210. Cannot assign requested address (localhost:9000)

======================================================================
ERROR: test_get_records (integration.hooks.test_clickhouse_dbapi.ClickHouseDbApiHookTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/dbapi/cursor.py", line 111, in execute
    response = execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 361, in execute
    with self.disconnect_on_error(query, settings):
  File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 305, in disconnect_on_error
    self.establish_connection(settings)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 292, in establish_connection
    self.connection.force_connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 254, in force_connect
    self.connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 416, in connect
    raise err
clickhouse_driver.errors.NetworkError: Code: 210. Cannot assign requested address (localhost:9000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/airflow/tests/integration/hooks/test_clickhouse_dbapi.py", line 8, in test_get_records
    records = ClickHouseDbApiHook().get_records(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 261, in get_records
    return self.run(sql=sql, parameters=parameters, handler=fetch_all_handler)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 398, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 453, in _run_command
    cur.execute(sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/dbapi/cursor.py", line 117, in execute
    raise OperationalError(orig)
clickhouse_driver.dbapi.errors.OperationalError: Code: 210. Cannot assign requested address (localhost:9000)

----------------------------------------------------------------------
Ran 2 tests in 0.317s

FAILED (errors=2)
```

**Comment by markusf1895** [comment]
a simple python env with clickhouse-driver works just fine. see https://github.com/mymarilyn/clickhouse-driver/issues/415

**Comment by markusf1895** [comment]
use 'clickhouse://localhost:9000'
