### ISSUE TITLE
Circular Import Error with `ExternalPythonOperator` in Airflow whenever importing airflow_clickhouse_plugin.hooks.clickhouse

### ISSUE THREAD

**Issue by nimanov** [bryzgaloff/airflow-clickhouse-plugin#89]
**Problem:**
As a team we are switching to the `ExternalPythonOperator` instead of `PythonOperator`. Thus we are creating a pre-existing virtual environments for the tasks that were working already.

The environment is created with below steps:

```bash
python3.8 -m venv venv1
pip install -r requirements.txt --constraint constraints.txt
```

Where `requirements.txt` is:
```plaintext
airflow-clickhouse-plugin==1.4.0
apache-airflow-providers-hashicorp==3.8.0
```

and `constraints.txt` is:
```plaintext
apache-airflow==2.8.1
```
The Python version is 
```plaintext
Python Version: 3.8.12
```

**The Error Message that I get:**

```plaintext
  [2024-08-27, 14:36:39 +04] ERROR - Unable to load the config, contains a configuration error.
  Traceback (most recent call last):
    File "/usr/local/lib/python3.8/logging/config.py", line 93, in _resolve
      found = getattr(found, n)
  AttributeError: partially initialized module 'airflow' has no attribute 'utils' (most likely due to a circular import)
  
  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/usr/local/lib/python3.8/logging/config.py", line 542, in configure
      formatters[name] = self.configure_formatter(
    File "/usr/local/lib/python3.8/logging/config.py", line 674, in configure_formatter
      c = _resolve(cname)
    File "/usr/local/lib/python3.8/logging/config.py", line 96, in _resolve
      found = getattr(found, n)
  AttributeError: partially initialized module 'airflow' has no attribute 'utils' (most likely due to a circular import)
  
  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "/tmp/venv-call7va5jd85/script.py", line 48, in <module>
      res = update_clickhouse_data(*arg_dict["args"], **arg_dict["kwargs"])
    File "/tmp/venv-call7va5jd85/script.py", line 28, in update_clickhouse_data
      from airflow_clickhouse_plugin.hooks.clickhouse import ClickHouseHook
    File "/home/airflow/airflow/envs/venv1/lib/python3.8/site-packages/airflow_clickhouse_plugin/hooks/clickhouse.py", line 6, in <module>
      from airflow.hooks.base import BaseHook
    File "/home/airflow/airflow/envs/venv1/lib/python3.8/site-packages/airflow/__init__.py", line 68, in <module>
      settings.initialize()
    File "/home/airflow/airflow/envs/venv1/lib/python3.8/site-packages/airflow/settings.py", line 546, in initialize
      LOGGING_CLASS_PATH = configure_logging()
    File "/home/airflow/airflow/envs/venv1/lib/python3.8/site-packages/airflow/logging_config.py", line 74, in configure_logging
      raise e
    File "/home/airflow/airflow/envs/venv1/lib/python3.8/site-packages/airflow/logging_config.py", line 69, in configure_logging
      dictConfig(logging_config)
    File "/usr/local/lib/python3.8/logging/config.py", line 808, in dictConfig
      dictConfigClass(config).configure()
    File "/usr/local/lib/python3.8/logging/config.py", line 545, in configure
      raise ValueError('Unable to configure formatter 'airflow'')
  ValueError: Unable to configure formatter 'airflow'
```

I have tried different versions of the airflow-clickhouse-plugin get the same problem. What is the problem?

**Comment by bryzgaloff** [comment]
Hi @nimanov,

Thank you for the detailed report and the steps to reproduce the issue.

Based on the information provided, I’m unable to pinpoint the exact cause of the error. However, I don’t believe the problem is directly related to the Airflow ClickHouse Plugin. It’s more likely an issue with your environment configuration or something related to Airflow itself.

Do you have any updates on this issue? Were you able to resolve it? If so, please share your findings—it might be helpful for others facing similar challenges!

If the issue is still unresolved, I can provide only a few generic recommendations:
- Double-checking the compatibility of your Airflow version and its dependencies with the plugin.
- Using the official constraints file when installing Airflow and its providers.
- Reviewing your Airflow logging configuration to rule out any conflicts.
